name: graintraide
services:
  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '172.17.0.1:5432:5432'
    healthcheck:
      test: CMD-SHELL ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: test_password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - postgis:/var/lib/pgadmin4/servers.json

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    volumes:
      - ./auth-service:/auth-service
    depends_on:
      - db
      - kafka
    environment:
      - DATABASE_URL=postgresql://admin:test_password@db/postgres

  item-service:
    build: ./item-service
    ports:
      - "8002:8000"
    volumes:
      - ./item-service:/item-service
    depends_on:
      - db
      - kafka
    environment:
      - DATABASE_URL=postgresql://admin:test_password@db/postgres
  
  telegram-bot:
    build: ./telegram-service
    ports:
      - "8003:8000"
    depends_on:
      - db
      - kafka
    volumes:
      - ./telegram-service:/telegram-service

  kafka:
    image: apache/kafka:3.8.0
    ports:
      - "9092:9092"

volumes:
  postgres_data:
  postgis:
