name: grain-dev
services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    networks:
      - grain-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  chat-room:
    build: ./chat-room
    restart: always
    env_file:
      - ./chat-room/.env
    ports:
      - "8001:8001"
    volumes:
      - ./chat-room:/chat-room
    networks:
      - grain-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  notifications:
    build: ./notifications
    restart: always
    env_file:
      - ./notifications/.env
    ports:
      - "8002:8002"
    volumes:
      - ./notifications:/notifications
    networks:
      - grain-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  grain-network:
    driver: bridge
