version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:test_password@db/postgres

  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test_password
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - '172.17.0.1:5432:5432'
    healthcheck:
      test: CMD-SHELL ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: test_password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:8080:8080"
    volumes:
      - ../servers.json:/pgadmin4/servers.json
