name: graintraide-dev
services:
  db:
    extends:
      file: docker-compose.yaml
      service: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev_password
    ports:
      - '5432:5432'

  pgadmin4:
    extends:
      file: docker-compose.yaml
      service: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.com
      PGADMIN_DEFAULT_PASSWORD: dev_password
      PGADMIN_LISTEN_PORT: 8080

  rabbitmq:
    extends:
      file: docker-compose.yaml
      service: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dev_user
      RABBITMQ_DEFAULT_PASS: dev_password

  redis:
    extends:
      file: docker-compose.yaml
      service: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    # image: backend:dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://admin:dev_password@db:5432/postgres
      - RABBITMQ_URL=amqp://dev_user:dev_password@rabbitmq:5672/
      - RABBITMQ_VHOST=/
      - JWT_SECRET=dev_secret
      - JWT_EXPIRES_IN=3600
      - ALGORITHM=HS256
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notifications:
    build: ./notifications
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./notifications:/app
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://admin:dev_password@db:5432/postgres
      - RABBITMQ_URL=amqp://dev_user:dev_password@rabbitmq:5672/
      - RABBITMQ_VHOST=/
      - JWT_SECRET=dev_secret
      - JWT_EXPIRES_IN=3600
      - ALGORITHM=HS256
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
      - rabbitmq
      - backend
      - redis
  
  frontend:
    build: 
      context: ./frontend
      # dockerfile: Dockerfile.dev
    # image: frontend:dev
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:8000
      - VUE_APP_NOTIFICATIONS_URL=http://localhost:8001
      - VUE_APP_RABBITMQ_URL=amqp://dev_user:dev_password@rabbitmq:5672/
      - VUE_APP_RABBITMQ_VHOST=/
      - VUE_APP_MAPBOX_TOKEN=pk.eyJ1Ijoia2l2YXNjaGVua28iLCJhIjoiY20zb2l1bTl4MDRrazJscXRxZ3YwMXdycyJ9.S915p8_E1L5u8yB3dypUpw
    command: command sh -c "npm install && npm run serve"
    depends_on:
      - backend
