services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ZOOKEEPER_PORT_NUMBER: 2181
      KAFKA_ZOOKEEPER_HOST: zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 6000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
      KAFKA_ZOOKEEPER_SYNC_TIME_MS: 2000
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami/kafka
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_DIR: /opt/bitnami/zookeeper/logs
      ZOO_LOG4J_PROP: INFO,ROLLINGFILE
      ZOO_LOG4J_LOG_DIR: /opt/bitnami/zookeeper/logs
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    depends_on:
      - kafka

volumes:
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local