butch = [
    {
        "title": "Sell wheat 2 grade",
        "description": "protein 45%",
        "price": 234.58,
        "currency": "USD",
        "amount": 360,
        "measure": "metric ton",
        "terms_delivery": "FCA",
        "country": "Ukraine",
        "region": "Cherkasy Oblast",
        "latitude": 49.305825,
        "longitude": 31.946946,
        # "id": 1
    },
    {
        "title": "Buy wheat 2 grade",
        "description": "protein >= 40%",
        "price": 218.23,
        "currency": "USD",
        "amount": 900,
        "measure": "metric ton",
        "terms_delivery": "FOB",
        "country": "Ukraine",
        "region": "Odesa Oblast",
        "latitude": 45.34172,
        "longitude": 28.800218,
        # "id": 2
    },
    {
        "title": "Buy wheat 2 grade",
        "description": "protein >= 39%",
        "price": 228.23,
        "currency": "USD",
        "amount": 1000,
        "measure": "metric ton",
        "terms_delivery": "FOB",
        "country": "Ukraine",
        "region": "Odesa Oblast",
        "latitude": 45.34172,
        "longitude": 28.800218,
        # "id": 3
    },
    {
        "title": "Buy wheat 3 grade",
        "description": "protein >= 38%",
        "price": 208.23,
        "currency": "USD",
        "amount": 2500,
        "measure": "metric ton",
        "terms_delivery": "FOB",
        "country": "Ukraine",
        "region": "Odesa Oblast",
        "latitude": 45.34172,
        "longitude": 28.800218,
        # "id": 4
    },
    {
        "title": "Sell wheat 2 grade",
        "description": "protein >= 38%",
        "price": 268.23,
        "currency": "USD",
        "amount": 500,
        "measure": "metric ton",
        "terms_delivery": "FSA",
        "country": "Ukraine",
        "region": "Kyiv Oblast",
        "latitude": 49.659466,
        "longitude": 30.974681,
        # "id": 5
    },
    {
        "title": "Sell wheat 2 grade",
        "description": "protein >= 38%",
        "price": 278.23,
        "currency": "USD",
        "amount": 600,
        "measure": "metric ton",
        "terms_delivery": "FSA",
        "country": "Ukraine",
        "region": "Kyiv Oblast",
        "latitude": 49.659466,
        "longitude": 30.974681,
        # "id": 6
    },
]
