name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      REMOTE_HOST: 65.108.68.57
      REMOTE_USER: root
      REMOTE_PATH: /home/kivaschenko/graintrade-info

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Copy project to remote Server
        run: |
          rsync -avz --delete \
            -e "ssh -p 22 -o StrictHostKeyChecking=no" \
            ./ ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/

      - name: Remote build and up
        run: |
          ssh ${REMOTE_USER}@${REMOTE_HOST} <<'EOF'
            cd ${REMOTE_PATH}
            docker compose build
            docker compose up -d
          EOF
        
