name: Trigger auto deployment for web-app-graintrade

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/web-app-graintrade-AutoDeployTrigger-c59afced-7a25-4b5a-87af-42085d3c9dc2.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBAPPGRAINTRADE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBAPPGRAINTRADE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBAPPGRAINTRADE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        run: |
          docker build \
            --build-arg PGHOST=${{ secrets.PGHOST }} \
            --build-arg PGUSER=${{ secrets.PGUSER }} \
            --build-arg PGPORT=${{ secrets.PGPORT }} \
            --build-arg PGDATABASE=${{ secrets.PGDATABASE }} \
            --build-arg PGPASSWORD=${{ secrets.PGPASSWORD }} \
            -t ca6a3704c17cacr.azurecr.io/web-app-graintrade:${{ github.sha }} .
          docker push ca6a3704c17cacr.azurecr.io/web-app-graintrade:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: web-app-graintrade
          resourceGroup: graintrade-info-rg
          imageToBuild: ca6a3704c17cacr.azurecr.io/web-app-graintrade:${{ github.sha }}
          registryUrl: ca6a3704c17cacr.azurecr.io
          registryUsername: ${{ secrets.WEBAPPGRAINTRADE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBAPPGRAINTRADE_REGISTRY_PASSWORD }}

      - name: Set environment variables for container app
        run: |
          az containerapp envvar set \
            --name web-app-graintrade \
            --resource-group graintrade-info-rg \
            --env-vars \
              PGHOST=${{ secrets.PGHOST }} \
              PGUSER=${{ secrets.PGUSER }} \
              PGPORT=${{ secrets.PGPORT }} \
              PGDATABASE=${{ secrets.PGDATABASE }} \
              PGPASSWORD=${{ secrets.PGPASSWORD }} \
              TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              JWT_SECRET=${{ secrets.JWT_SECRET }} \
              JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }} \
              MAIL_HOST=${{ secrets.MAIL_HOST }} \
              MAIL_PORT=${{ secrets.MAIL_PORT }} \
              MAIL_USER=${{ secrets.MAIL_USER }} \
              MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
